spring:
  datasource:
    url: jdbc:h2:file:C:\\sandy2friends\\backend\\rest\\demo
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    data: classpath:start.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  security:
    user:
      name: user
      password: password
management:
  endpoints:
    web:
      exposure:
        include: beans,env
  endpoint:
    info:
      enabled: true